### ISSUE TITLE
Goodplay using only local roles

### ISSUE THREAD

**Issue by EricVS** [goodplay/goodplay#9]
Hi Ben, 
I've tried your suggestion using the src in meta/main.yml and although it downloads the repository from our local Stash server, it still throws an error trying to use Galaxy. I've put the complete error in a Gist:
https://gist.github.com/EricVS/0a79bdda83f2a91f1500

Wouldn't it be simpler if goodplay looks for the roles in the path as specified in the ansible.cfg instead of per default contacting Galaxy? Just an idea. Looking forward to your answer. 

Kind regards, 
EricVS

**Comment by benjixx** [comment]
@EricVS As you haven't added the actual Ansible files (or even better the shortest example reproducing the problem) I can only speculate about what causes the error.

A role's dependencies are resolved recursively. So, when ``ansible-galaxy`` installs the role referenced in ``meta/main.yml``, the referenced role itself may have dependencies mentioned in its own ``meta/main.yml``. To me it looks like the error is caused by other dependencies being not declared properly. If you don't want ``ansible-galaxy`` to use its online service in this case you would have to define the ``src`` attribute and optionally ``version``attribute for the dependency as well.

Regarding the feature idea of looking at the defined ``roles_path`` in ``ansible.cfg``, I'm currently not too convinced to implement that. I usually use goodplay to run tests in a continuous integration environment like e.g. Travis CI or Jenkins CI. This means that when checking out the source code, I would like to easily be able to run the tests, which includes auto-installation of all dependencies and its appropriate versions. When I would allow to use the ``roles_path`` defined in ``ansible.cfg`` the user would need to do the preparation on its own, and the role in the ``roles_path`` I depend on would need to match the role under test's expected version.

**Comment by EricVS** [comment]
@benjixx Thank you for your answer Ben. I did at first specify the `src` attribute only in the first called dependent role and got the error in the Gist. I assumed what you indicate and put the `src` attribute in all of the `meta/main.yml` files of those roles but got the same error. 

i understand that you prefer to use a continuous integration tool like Travis / Jenkins CI but that's not an option for me I believe. As long as I stick to standard installations it will be ok but our in-house software packages are stored on local Artifactory servers that are not accessible from the outside so all my playbooks would fail at some point. That's why I thought of having something like a `--local` parameter to limit searches for roles to local path (relative to execution or from the roles_path in ansible.cfg). 

I'll provide you example files I used this weekend, thanks again for your assistance. 

Kind regards, 
Eric

**Comment by benjixx** [comment]
@EricVS I just had another look at the goodplay source code and tests as I wanted you to offer another solution. But when looking at the test cases again (especially [these ones](https://github.com/goodplay/goodplay/blob/42953e4/tests/test_ansible_role_support_integration.py#L106-L178)) I recognized that the test cases are not what they were intended to be. Actually they were meant to prove that dependent roles could live beside each other but in the test cases roles are compressed during test preparation to allow ``ansible-galaxy`` to fetch them.

I will need to have another look at this whole topic. I understand that this is a blocker for you and will try to get this higher prioritized on my list.

**Comment by EricVS** [comment]
@benjixx Thanks for the feedback and the explanation. I've forked your repo and am starting to use that for testing purposes in a virtualenv too, just to keep in line with any modifications you make prior to publishing. 
Although i would very much like to use Goodplay already, it's not a blocker at this moment so don't feel pressured at all. I still have a lot of work and rearranging to do on my playbooks.

**Comment by benjixx** [comment]
@EricVS I have prepared a first work-in-progress PR #12 for this. It allows you to run with a ``--use-local-roles`` switch which basically runs Ansible with the following roles paths (in order):

1. ``<role-under-test>/..`` (parent directory of role under test; this is currently also used when running without the switch and could have side effects, which need to be addressed separately)
2. ``ansible.constants.DEFAULT_ROLES_PATH`` (so we're using whatever Ansible already thinks is its default role path, may it be configured via ``ansible.cfg`` or ``ANSIBLE_ROLES_PATH`` environment variable)
3. ``<installed_roles_path>`` (path to the roles that could be successfully get resolved via ``ansible-galaxy``)

Please give it a try and let me know if this solves your problem. Also, let me know when you have any other feedback on this.

**Comment by EricVS** [comment]
@benjixx Thank you for that. I haven't had time yet to continue my tests with goodplay. Had to cleanup, reorganize and do a lot of Ansible stuff on our playbooks. I will dedicate a lot more time to goodplay and integrating it with our playbooks (or vice versa :-)) starting tomorrow. 
I'll keep you posted of anything that I encounter.

**Comment by EricVS** [comment]
@benjixx I pulled in your feature branch but am getting errors at the make stage. This is what I did:
git fetch upstream (your repo)
git merge upstream/master
git merge upstream/feature/use-local-roles
make 
The full output can be found in this gist:
https://gist.github.com/EricVS/c3fef3a51831f46906a4

Looking forward to your feedback.

**Comment by benjixx** [comment]
@EricVS The test that failed was ran against latest ``ansible@devel``.

There was a ``wait_for`` task expected to fail but it wasn't. [This line](https://gist.github.com/EricVS/c3fef3a51831f46906a4#file-gistfile1-txt-L176) was expected to have ``"failed": true`` returned from Ansible which was not the case. So, it is actually an Ansible bug.

As the nightly build of goodplay passed successful [this morning](https://travis-ci.org/goodplay/goodplay/builds/114991746), I thought it could have been a temporary problem on the ``ansible@devel`` branch... which led me to this one (ansible/ansible@dbff3a6bbc3732cb7f2f4e7ed1e3f4e91661cd5d) which could probably be the root cause. You could verify this by running ``make clean test`` again.

**Comment by benjixx** [comment]
PR #12 addresses this problem and has just been merged.
